import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import MobileSidebar from "@/components/MobileSidebar";

const local = localFont({ src: "../public/ITCAvantGardePro-Md.otf" });

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${local.className} w-screen max-w-screen`}>
        <Navbar />
        {children}
        <Footer />
        <MobileSidebar />
      </body>
    </html>
  );
}
